= 互換性

== Emacs

CIDERはEmacs 26.1+をサポートしています。より一般的には、実現可能で、メンテナンスのオーバーヘッドを増やさない限り、Emacsの最後の3つのメジャーリリースをサポートするようにしています。

NOTE: 私たちは、現在の安定したDebianとRHEL GNU/LinuxディストリビューションにバンドルされているEmacsをサポートすることに特別な注意を払っています。

== nREPL

CIDERはnREPL 0.6+をサポートしています。

NOTE: 私たちは、現在の安定したLeiningenとBootのリリースにバンドルされているnREPLをサポートすることに特別な注意を払っています。

== Java

CIDERは、Java 8、Java 11、Java 17、および最新のラピッドリリースバージョン（Java 18など）を公式に対象としています。 一般的には、現在オラクルが公式にサポートしているすべてのJavaリリースをサポートすることを目指しています。

NOTE: Java の要件は ``cider-nrepl`` の要件とほぼ同じです。

Linuxでは、JDKソースとjavadocsがインストールされていることを確認する必要もあります。 xref:troubleshooting.adoc#navigation-to-jdk-sources-doesnt-work[Troubleshooting] にコマンドの例があります。

== Clojure

CIDERはClojure 1.8+をターゲットにしています。Clojureにはサポートされるリリースの概念がないので、ターゲットとする最小バージョンを決定するために少し独創的になる必要があります。

最低限必要なClojureバージョンは、現在  https://clojure.org/news/2019/02/04/state-of-clojure-2020[State of Clojure] 調査からのデータを使って導き出されています。一般的に、私たちはClojureリリースの使用率が5%を下回ったら、そのリリースを削除する対象になると考えています。メンテナンスの負担を減らすか、CIDERの大きな改善の可能性を開く場合にのみ行います。

== ClojureScript

現在、私たちはClojureとClojureScriptのサポートに同じポリシーを適用しています。

== 互換性マトリックス

NOTE: 非常に長い間、CIDERとcider-nreplは同期してリリースされていたが、CIDER 0.18で変わった。実際のリリースはCIDER 0.23で初めて分かれました。

以下はCIDERの公式互換性マトリックスです。

.Compatibility Matrix
|===
| CIDER | Emacs | nREPL | cider-nrepl | Required JDK | Required Clojure

| 0.22
| 25.1
| 0.6
| 0.22
| 8
| 1.8

| 0.23
| 25.1
| 0.6
| 0.22
| 8
| 1.8

| 0.24
| 25.1
| 0.6
| 0.24
| 8
| 1.8

| 0.25
| 25.1
| 0.6
| 0.25
| 8
| 1.8

| 0.26
| 25.1
| 0.6
| 0.25
| 8
| 1.8

| 1.0
| 25.1
| 0.6
| 0.25
| 8
| 1.8

| 1.1
| 25.1
| 0.6
| 0.25
| 8
| 1.8

| 1.2
| 26.1
| 0.9
| 0.27
| 8
| 1.8

| 1.3
| 26.1
| 0.9
| 0.28
| 8
| 1.8

| 1.4
| 26.1
| 0.9
| 0.28
| 8
| 1.8

| 1.5
| 26.1
| 0.9
| 0.28
| 8
| 1.8

| 1.6
| 26.1
| 1.0
| 0.29
| 8
| 1.8

| 1.7
| 26.1
| 1.0
| 0.30
| 8
| 1.8

|===

TIP: また、いくつかの CIDER 変数の値を調べることで、特定の CIDER バージョンの必要条件をチェックすることもできます。例えば、必要な `cider-nrepl` のバージョンは `cider-required-middleware-version` にあります。
