= 追加パッケージ

あなたの Clojure プログラミング体験を向上させることができる多くの追加 Emacs パッケージがあります。ここに挙げたマイナーモードの大部分は、最適な効果を得るために `cider-repl-mode` と `clojure-mode` の両方で有効にする必要があります。

ここにリストされたパッケージは3つのカテゴリに属します：

* CIDER 拡張
* Clojure プログラミングに有用な汎用 Emacs パッケージ
* CIDER 代替

== CIDER拡張機能

重要：インストールした拡張機能のバージョンがCIDERのバージョンと互換性があることを確認してください。

CIDER拡張は通常、CIDERのEmacs Lisp API上に構築されたEmacsパッケージです。 その中には追加のnREPLミドルウェアも同梱されているものもあります(`clj-refactor`など)。通常、ミドルウェアに依存するパッケージはCIDERのミドルウェア注入機能にフックし、独自の機能も自動的に注入します。

注意: 現在、CIDERの「公式な」拡張機能はなく、リストにあるパッケージはCIDERのコアチームによってメンテナンスされていないことに注意してください。その品質やメンテナンスのレベルは大きく異なる可能性があります。

=== clj-decompiler

https://github.com/bsless/clj-decompiler.el[clj-decompiler] を使うと、ClojureコードをJavaバイトコードに素早くデコンパイルできます。これは https://github.com/clojure-goes-fast/clj-java-decompiler[clj-java-decompiler] に基づいています。

=== clj-refactor

https://github.com/clojure-emacs/clj-refactor.el[clj-refactor] は`clojure-mode`とCIDERの上に構築され、大量の追加機能(例えば、式をスレッド/アンスレッドする機能、用例の検索と置換、letバインディングの導入、関数の抽出など)を追加します。

機能の完全なリストは https://github.com/clojure-emacs/clj-refactor.el/wiki[ここ] から入手できる。

将来的には、この機能のいくつかを `clojure-mode` と CIDER 自身に組み込みたいと考えています。

=== emidje

https://github.com/nubank/emidje[Emidje] は  https://github.com/marick/Midje[Midje]  用のテストランナー、レポートビューア、フォーマットツールです。

Emidje は CIDER を拡張して、`cider-test.el` が `clojure.test` テストをサポートしているのと同様の方法で Midje テストをサポートしています。実際、Emidje のほとんどの機能は `cider-test.el` の機能に強くインスパイアされています。

=== kaocha-runner

https://github.com/magnars/kaocha-runner.el[kaocha-runner] は https://github.com/lambdaisland/kaocha[Kaocha] をEmacsに統合します。

=== helm-cider

https://github.com/clojure-emacs/helm-cider[helm-cider]は特定のCIDERコマンド（例えば`cider-apropos`）のためのHelmインターフェースを提供します。

=== cider-hydra

https://github.com/clojure-emacs/cider-hydra[cider-hydra] は、関連するCIDERコマンドのグループをナビゲートする素晴らしい方法を提供します。

よりファンシーな https://github.com/justbur/emacs-which-key[which-key] と考えることができます。

=== flycheck-clj-kondo

https://github.com/borkdude/flycheck-clj-kondo/[flycheck-clj-kondo] はClojure用のFlycheckチェッカーで、 https://github.com/borkdude/clj-kondo[clj-kondo] を介して、入力中に即座にclojureコードのリンティングを行います。

https://github.com/borkdude/clj-kondo[clj-kondo] は、バグだらけのコードを書かないようにする素晴らしい方法です。

=== squiggly-clojure

https://github.com/clojure-emacs/squiggly-clojure[squiggly-clojure] は、 https://github.com/jonase/eastwood[eastwood] 、 http://typedclojure.org/[core.typed]、https://github.com/jonase/kibit[kibit] といったツールを使ったClojure用のフライチェック・チェッカーです。

=== sayid

http://clojure-emacs.github.io/sayid/[sayid] は、CIDERに内蔵されている基本的なトレース機能の強力な代替機能です。

== 汎用Emacs拡張

以下のリストにあるパッケージのほとんどは、標準的なEmacsのマイナーモードで、ほとんどのメジャーモードで動作しますが、ClojureのようなLispライクな言語では特に便利です。

=== subword-mode

REPLで編集コマンド(`forward-word`、`backward-word`など)の `CamelCase` サポートを有効にすることは、Javaのクラス名やメソッド名を扱うことが多いので、とても便利です。Emacs組み込みのマイナーモード `subword-mode` はそのような機能を提供する：

[source,lisp]
----
(add-hook 'cider-repl-mode-hook #'subword-mode)
----

=== Paredit

Clojure（または他のLisp）コードを編集するときは、 http://mumble.net/~campbell/emacs/paredit.html[paredit] の使用を強く推奨します。 おそらく `clojure-mode` バッファですでに使っていることでしょう(もし使っていないなら、使うべきでしょう)。また、REPLバッファでも `paredit` を有効にするとよいでしょう：

[source,lisp]
----
(add-hook 'cider-repl-mode-hook #'paredit-mode)
----

==== RETキーのPareditバインディングの解除

Paredit の最近のバージョン (25+) では `RET` は `paredit-RET` にバインドされている。このため、`paredit-mode`が有効になっているときにreplが予期しない動作をすることがあります。例えば、`RET`を押した後に最後のフォームを評価せずにハングしてしまうようなことがあります。

このPareditの動作を無効にするには、`init.el`に以下を追加してください：

[source,lisp]
----
(define-key paredit-mode-map (kbd "RET") nil)
----

=== Smartparens

https://github.com/Fuco1/smartparens[smartparens] はpareditの優れた代替手段です。多くのClojureハッカーが最近これを採用しているので、あなたも試してみるとよいでしょう。REPLバッファで`smartparens`を有効にするには、以下のコードを使います：

[source,lisp]
----
(add-hook 'cider-repl-mode-hook #'smartparens-strict-mode)
----

=== rainbow-delimiters

https://github.com/Fanael/rainbow-delimiters[RainbowDelimiters] は、括弧、波括弧、中括弧をその深さに応じてハイライトするマイナーモードです。各レベルは異なる色でハイライトされます。これによって、マッチする区切り記号を見つけやすくなり、コード内の方向が定まり、どのステートメントが指定された深さにあるかがわかります。すでにRainbowDelimitersがインストールされていれば、REPLで次のように有効にすることができる：

[source,lisp]
----
(add-hook 'cider-repl-mode-hook #'rainbow-delimiters-mode)
----

=== eval-sexp-fu

https://github.com/hchbaw/eval-sexp-fu.el[eval-sexp-fu] は式を評価するときにいくつかの視覚的なフィードバックを提供します。 https://github.com/clojure-emacs/cider-eval-sexp-fu[cider-eval-sexp-fu] は`eval-sexp-fu`にCIDER統合を提供します。

[source,lisp]
----
(require 'cider-eval-sexp-fu)
----

== 代替

重要: 一般的にClojureプログラミング環境を混在させるのは良くない。一度に1つの環境だけを実行するようにしてください。

このセクションでは、Emacs用のClojureプログラミング環境を提供する他のEmacsパッケージを列挙します。

=== Inf-clojure

本パッケージはClojureサブプロセス(REPL)との基本的なインタラクションを提供します。人気のある inferior-lisp パッケージからのアイデアに基づいています。

https://github.com/clojure-emacs/inf-clojure[inf-clojure] には2つのコンポーネントがあります - 自動補完のある素敵なClojure REPLと、マイナーモード(`inf-clojure-minor-mode`)であり、REPLでフォームを直接評価するコマンドでclojure-modeを拡張します。

基本的にはCIDERの単純な代替で、CIDERの機能のサブセットを提供します。
