= 注意事項
:experimental:

CIDERは確かに完璧ではなく、誰もが知っておくべきいくつかの制限がある。

== ClojureScriptの制限

現在、以下の機能はClojureScript開発ではサポートされていません：

* リロード
* テストの実行
* トレース
* デバッグ (デバッガをClojureScriptに移植することに特化した https://github.com/clojure-emacs/cider/issues/1416[このチケット] をチェックしてください)
* Enlighten

現在のところ、同じnREPLセッションでClojureとClojureScriptの両方を評価するサポートはありません。Piggiebackがアクティブな場合、コード評価とすべての機能はClojureScriptを想定しています。

== Microsoft Windows

=== 行区切り文字

Microsoft Windowsでは、JVMのデフォルトの行区切り文字列は `\r\n` で、EmacsではJVMが出力する行の最後に `+^M+` 文字として表示されることがある。1つのオプションは、 http://stackoverflow.com/questions/10098925/m-character-showing-in-clojure-slime-repl/11787550#11787550[こちら] で詳しく説明されているように、これらの文字を表示しないように `buffer-display-table` を設定することである（`slime-repl-mode-hook` を `cider-repl-mode-hook` に変更する）。あるいは、JVM起動時にシステムプロパティ `line.separator` を `\n` に設定すると、キャリッジリターンが出力されなくなり、すべてのサイダーバッファの出力が修正されます。そうするには、 `~/.lein/profiles.clj` の `:jvm-opts` に `"-Dline.separator=\”\n\""` を追加してください。

=== jarファイルの定義検索

ソース検索コマンドを `.jar` ファイルで動作させるには、http://www.7-zip.org/[7zip] または `pkunzip` をインストールして、そのインストールフォルダを Emacs の `exec-path` に追加する必要があります。以下はその例です：

[source,lisp]
----
(add-to-list 'exec-path "C:/Program Files/7-Zip")
----

== powershell.el

powershellの劣ったシェル・モードは、ロード時にCIDERのREPL出力を切り捨てます。回避策として

[source,lisp]
----
(require 'powershell)
----

をEmacsの設定から削除してください。

== ClojureCLRサポート

CIDERは現在、非常に基本的なClojureCLRをサポートしています（ArcadiaのnREPLサーバー経由）。その理由は以下の通りです：

* nREPL自体はJVM上でのみ動作します（内部的にJava APIを活用しているため）。 https://github.com/clojure/clr.tools.nrepl[nREPL port for ClojureCLR] がありますが、活発にメンテナンスされておらず、Clojure nREPLのようには動作しません。
* `cider-nrepl`は内部的に多くのJavaコードを使用しています。

これらの問題は克服できないものではありませんが、現在のロードマップの範囲を超えています。 もし誰かがそれらに取り組みたいのであれば、喜んで支援を提供します。

== 依存関係のインジェクションと Leiningen pedantic: アボートモード

現在、インジェクションは nREPL 依存性のオーバーライドを作成し、Leiningen もそれをプルしているため、`:pedantic? :abort` が設定されていると REPL の起動に失敗します。これに対処するにはいくつかの方法があります：

* `pedantic? :abort` の設定を削除する。
* xref:basics/middleware_setup.adoc#setting-up-a-standalone-repl[standalone REPL] セクションで説明されているように `~/.lein/profiles.clj` を編集して依存関係を提供してください。
* `cider-injected-nrepl-version` の値を Leiningen にバンドルされているものと同じ nREPL バージョンに調整してください。
