= よくある質問

== CIDERとは何の略ですか？

CIDERは、**C**lojure **I**nteractive **D**evelopment **E**nvironment that **R**ocksの略です。

== 本当にロックなのか？

そうだよ。

== 「jack-in」は『ニューロマンサー』からの引用ですか？

そうです。

== この「jack-in」は『マトリックス』のことを指しているのでしょうか？

そうです。

== CIDERとnrepl.elの関係は？

`nrepl.el` はバージョン0.3でCIDERに改名されました。nREPLサーバ自身との混同を避けるためと、CIDERがEmacs用のnREPLクライアント以上のものであるという事実をよりよく反映するためです。 さらに、この新しい名前は、代替の評価バックエンド(例えば、Clojure 1.8で導入されたソケットREPL)をサポートする機会を与えてくれます。

== CIDERとmonroeの関係は？

https://github.com/sanel/monroe[monroe] は基本的に、nREPLミドルウェアに依存し始める前の古いCIDERバージョンのフォークです。 MonroeはよりシンプルなUXを選び、非常にREPL中心で、組み込みのnREPL opsのみを使用しています（cider-nreplに大きく依存しているCIDERとは異なります）。

== CIDERとinf-clojureの関係は？

https://github.com/clojure-emacs/inf-clojure[inf-clojure] は`comint` EmacsパッケージをベースにしたREPLを提供します - 基本的にはEmacsの中で外部のREPLプロセスを実行することになります（ネットワーク接続は関係ありません）。 この利点は、外部依存が全くないことです。REPLプロセスを開始するコマンド(例えば`lein repl`)が必要なだけです。

== IntelliJのCursiveは最高のClojure IDEではないですか？

Cursiveはかなり素晴らしいです！あなたのプログラミングの好み(IDEを使うか、あなたのニーズに合わせたカスタム編集体験を構築するか)によっては、CIDERよりも良い選択肢になるかもしれません。

== CIDERのリリースのコードネームはどうなっているのだろう？

コードネームは通常、CIDERのメンテナンス責任者（Bozhidar）のお気に入りの場所です。

ヒント：Bozhidarはスペインとアメリカ西海岸が大好きなので、本当に特別なリリースにはそれらに関連したコードネームをつける傾向があります（シアトル、カリフォルニア、アンダルシアなど）。

== なぜCIDERのウェブサイトは.mxドメインを使用しているのですか？

https://emacsredux.com/blog/2018/11/17/the-perfect-domain-for-emacs-projects/[Emacsプロジェクトに最適なドメイン] だからです。

== EmacsとClojureの両方に慣れていない場合、CIDERを使うのは良いアイデアですか？

CIDER自体には特に複雑なところはありませんが、Emacsを使いこなすのは人によっては少し難しいかもしれません。

一般的には、Emacsの "スターターキット "を使い、Emacsに関する良い本を手に入れることで、最初の学習経験をかなり簡略化できます(例えば、 https://www.masteringemacs.org/[Mastering Emacs] )。

https://github.com/bbatsov/prelude[Prelude] と http://spacemacs.org/[Spacemacs] は、あなたが使用を検討するかもしれないいくつかの素晴らしいEmacsディストリビューションです。

PreludeはCIDERの主要な作者自身によってメンテナンスされていますし、Spacemacsはvim難民にとって素晴らしい選択肢です（`evil-mode`によるvimエミュレーションに重点を置いているからです）。

== CIDERの安定版リリースは、あらかじめ決められたサイクルで行われるのですか？

安定版リリースは、メンテナが新しいリリースが必要だと感じたときに発行されます。メンテナンス担当者は通常、1年に少なくとも2-3回の安定版リリースを目指しています。

== CIDERにはロードマップがありますか？

正確なロードマップはありませんが、（近い）将来の大きな目標がいくつかあります：

* セッション管理を改善する（よりシンプルで予測可能なものにする）。
* ClojureScriptとClojureの機能を同等にする（現状では、多くの機能がClojureのみです）。
* 兄弟プロジェクト https://github.com/clojure-emacs/clj-refactor.el[clj-refactor] からの最も重要なリファクタリング機能をCIDERに統合します。

https://github.com/clojure-emacs/cider/blob/master/ROADMAP.md[roadmap document] に詳細があります。

注：もしあなたがロードマップからいくつかの項目に取り組みたいのであれば、Bozhidarは喜んであなたを助け、道案内します。

== CIDERの安定版リリースは、主要なClojureカンファレンスの前後によく起こるというのは本当ですか？

そうです。そのようなイベントでCIDERについて話す理由を提供したいのです。:-)

TIP: Bozhidarや他のCIDERコア開発者をClojureカンファレンスに招待して発表してもらうと、CIDERのリリースが増える可能性が高いです！

== CIDERのMELPA（スナップショット）ビルドはどれくらい不安定ですか？

かなり安定しています。重大なリグレッションが発生することはほとんどなく、通常は数時間以内に修正されます。MELPAビルドを使用することで、新機能にいち早くアクセスすることができ、また、メンテナのテストプロセスを支援することにもなります。

== CIDERをスナップショットビルドから最新の安定版にダウングレードできますか？

はい、できます。`cider` パッケージを削除し、`cider` を MELPA 安定版に固定し、再インストールするだけです。基本的には以下のようにします：

* `M-x package-remove cider` を実行してください。
* Emacs の設定に `(add-to-list 'package-pinned-packages '(cider . "melpa-stable") t)` を追加します。
* Emacs を再起動します (または設定をリロードします)
* `M-x package-install cider` を実行します。

== CIDERを特定の安定バージョンにダウングレードできますか？

いいえ、できません。残念ながら `package.el` はパッケージの過去のバージョンという概念をサポートしていません。

== CIDERは最終的にClojure 1.8のソケットREPLをサポートしますか？

多分。私たちの焦点はnREPLを最大限に活用することですが、将来的には追加のREPLサーバのサポートを追加するために時間を投資することを検討するかもしれません。

TIP: https://github.com/clojure-emacs/cider/blob/master/ROADMAP.md[roadmap] ドキュメントに、行うべき作業についての詳細な情報があります。

== CIDERは最終的にClojure 1.10 preplをサポートしますか?

上記と同じ答えです。一つ確かなことは、CIDERの目的には、プレーンなソケットREPLよりもpreplの方がずっと便利だということです。

== CIDERのnREPLミドルウェアはEmacs専用ですか？

全然違います。`cider-nrepl`の機能はエディタにとらわれず、様々なエディタプラグインに利用されています。代表的な例としては `vim-fireplace` や Visual Studio Code の `calva` などがあります。

== CIDERで利用可能なすべての設定オプションを見るには？

`M-x customize-group RET cider RET`。

== チェックアウトする価値のある面白いCIDERアドオンはありますか？

もちろんです！詳細は xref:additional_packages.adoc[additional packages] を参照してください。

== CIDERに関するヘルプはどこで手に入りますか？

マニュアルの xref:about/support.adoc[サポート] セクションを参照してください。

== CIDERで問題にぶつかったらどうすればいいですか？

慌てないでください！次のステップ - マニュアルの xref:troubleshooting.adoc[トラブルシューティング] セクションをご覧ください。

== どうすればプロジェクトを助けることができますか？

CIDERを支援する方法はたくさんあります。

* 資金を寄付する
* ドキュメントを改善する
* 未解決の問題を解決する
* バグレポートや改善提案の提出
* ブログ投稿やミートアップやカンファレンスでCIDERを宣伝する。
* CIDERチームのメンバーを招待し、MeetupやカンファレンスでCIDERについて話してもらう。
